<?php
return [
// Menú y navegación
'Iniciar sesión' => 'Log in',
'Actividades' => 'Activities',
'Calendario' => 'Calendar',
'Paquetes' => 'Packages',
'Registrarse' => 'Sign up',
'Administración' => 'Admin',
'Mi cuenta' => 'My account',
'Mis reservas' => 'My bookings',
'Salir' => 'Log out',

// index.php
'Sama Shala | Reserva actividades y espacios' => 'Sama Shala | Book activities and spaces',
'Clases, Terapias y Eventos' => 'Classes, Therapies and Events',
'Un espacio para tu Bienestar' => 'A space for your Wellbeing',
'Consulta nuestras próximas actividades y encuentra tu equilibrio interior.' => 'Check out our upcoming activities and find your inner balance.',
'Ver actividades' => 'View activities',
'¿Cómo funciona?' => 'How does it work?',
'Elige una actividad.' => 'Choose an activity.',
'Consulta sus próximas sesiones.' => 'Check its upcoming sessions.',
'Comprueba fecha, horario y plazas.' => 'Check the date, time and spots.',
'Reserva la sesión que te interese.' => 'Book the session you like.',
'Un proyecto basado en la disponibilidad' => 'A project based on availability',
'Descubre qué puedes hacer, su categoría, nivel y duración habitual.' => 'Discover what you can do, its category, level and usual duration.',
'Consulta cuándo se celebra cada actividad, en qué espacio y con qué profesor.' => 'Check when each activity takes place, in which space and with which teacher.',
'Plazas' => 'Spots',
'Comprueba el aforo y las plazas disponibles antes de realizar la reserva.' => 'Check the capacity and available spots before booking.',

'Todos los niveles' => 'All levels',
'Nivel inicial' => 'Beginner level',
'Nivel intermedio' => 'Intermediate level',
'Nivel avanzado' => 'Advanced level',
'Clase' => 'Class',
'Evento' => 'Event',
'Terapia' => 'Therapy',
'Programada' => 'Scheduled',
'Completa' => 'Full',
'Cancelada' => 'Cancelled',
'Finalizada' => 'Finished',

// actividades.php / detalle_actividad.php
'Actividades | Sama Shala' => 'Activities | Sama Shala',
'Catálogo' => 'Catalog',
'Consulta las actividades del centro y descubre sus próximas sesiones.' => 'Browse the center\'s activities and discover their upcoming sessions.',
'Categoría' => 'Category',
'Todas las categorías' => 'All categories',
'Tipo' => 'Type',
'Cualquier tipo' => 'Any type',
'Nivel' => 'Level',
'Cualquier nivel' => 'Any level',
'Filtrar' => 'Filter',
'Limpiar' => 'Clear',
'No se han encontrado actividades con los filtros seleccionados.' => 'No activities found with the selected filters.',
'Duración' => 'Duration',
'minutos' => 'minutes',
'Ver detalles' => 'View details',
'Sin imagen' => 'No image',
'Duración habitual:' => 'Usual duration:',
'Próxima:' => 'Next:',
'Disponibilidad' => 'Availability',
'plazas disponibles' => 'spots available',
'Lista de espera disponible' => 'Waitlist available',
'La actividad no existe o no está disponible.' => 'This activity does not exist or is not available.',
'← Volver a las actividades' => '← Back to activities',
'| Sama Shala' => '| Sama Shala',
'Especialidad del profesor:' => 'Teacher\'s specialty:',
'Próximas sesiones' => 'Upcoming sessions',
'Esta actividad todavía no tiene próximas sesiones disponibles.' => 'This activity has no upcoming sessions available yet.',
'Próximamente anunciaremos nuevas fechas.' => 'New dates will be announced soon.',
'Ver actividad' => 'View activity',
'de' => 'of',
'plazas disponibles de' => 'spots available out of',
'Sesión completa' => 'Session full',
'Ver sesión' => 'View session',

// sesiones.php / detalle_sesion.php
'Próximas sesiones | Sama Shala' => 'Upcoming sessions | Sama Shala',
'Consulta las actividades que se celebrarán próximamente.' => 'Check the activities coming up next.',
'Buscar por fecha' => 'Search by date',
'Buscar' => 'Search',
'Mostrar todas' => 'Show all',
'No hay sesiones disponibles para la fecha seleccionada.' => 'No sessions available for the selected date.',
'El identificador de la sesión no es válido.' => 'The session identifier is not valid.',
'El identificador no es válido.' => 'The identifier is not valid.',
'La sesión solicitada no existe.' => 'The requested session does not exist.',
'← Volver a la actividad' => '← Back to the activity',
'Profesor' => 'Teacher',
'Profesor:' => 'Teacher:',
'Espacio' => 'Space',
'Espacio:' => 'Space:',
'Ubicación' => 'Location',
'Ubicación:' => 'Location:',
'Fecha' => 'Date',
'Horario' => 'Time',
'Aforo:' => 'Capacity:',
'Observaciones:' => 'Notes:',
'plazas ocupadas' => 'spots taken',
'reservas confirmadas' => 'confirmed bookings',
'próximas sesiones' => 'upcoming sessions',
'Esta sesión ya ha finalizado.' => 'This session has already finished.',
'Esta sesión ha sido cancelada.' => 'This session has been cancelled.',
'Reservar una plaza' => 'Book a spot',
'Apuntarme a la lista de espera' => 'Join the waitlist',
'Inicia sesión para reservar' => 'Log in to book',

// reservar.php / procesar_reserva.php
'Identificador de sesión no válido.' => 'Invalid session identifier.',
'La sesión no existe.' => 'The session does not exist.',
'Esta sesión ya no admite reservas.' => 'This session no longer accepts bookings.',
'Confirmar reserva' => 'Confirm booking',
'Confirmar solicitud' => 'Confirm request',
'Fecha:' => 'Date:',
'Horario:' => 'Time:',
'Quedan %d plazas disponibles.' => 'There are %d spots left.',
'Al confirmar se creará una reserva.' => 'A booking will be created when you confirm.',
'La sesión está completa.' => 'The session is full.',
'Al confirmar entrarás en la lista de espera.' => 'You will join the waitlist when you confirm.',
'¿Cómo quieres pagar esta clase?' => 'How do you want to pay for this class?',
'Clase suelta' => 'Single class',
'(quedan %d usos)' => '(%d uses left)',
'La sesión no admite reservas.' => 'The session does not accept bookings.',
'La sesión ya ha comenzado.' => 'The session has already started.',
'Ya tienes una reserva confirmada.' => 'You already have a confirmed booking.',
'Ya estás en la lista de espera.' => 'You are already on the waitlist.',
'El paquete seleccionado no existe.' => 'The selected package does not exist.',
'El paquete seleccionado no está activo.' => 'The selected package is not active.',
'El paquete seleccionado no tiene usos disponibles.' => 'The selected package has no uses left.',
'El paquete seleccionado ha caducado.' => 'The selected package has expired.',
'La sesión está completa. Te hemos añadido a la lista de espera.' => 'The session is full. We\'ve added you to the waitlist.',
'La reserva se ha confirmado correctamente.' => 'Your booking has been confirmed successfully.',
'La reserva se ha cancelado.' => 'The booking has been cancelled.',

// login.php / registro.php / guardar_usuario.php
'Iniciar sesión' => 'Log in',
'La cuenta se ha creado correctamente. Ya puedes iniciar sesión.' => 'Your account has been created successfully. You can now log in.',
'El correo o la contraseña no son correctos.' => 'The email or password is incorrect.',
'Esta cuenta está desactivada.' => 'This account is disabled.',
'Debes iniciar sesión para acceder a esa página.' => 'You must log in to access that page.',
'Correo electrónico' => 'Email',
'Contraseña' => 'Password',
'Entrar' => 'Sign in',
'¿Todavía no tienes cuenta?' => 'Don\'t have an account yet?',
'Regístrate' => 'Sign up',
'Crear una cuenta' => 'Create an account',
'Regístrate para reservar plazas en las actividades.' => 'Sign up to book spots in activities.',
'Revisa los datos introducidos.' => 'Please check the details you entered.',
'Ya existe una cuenta con ese correo electrónico.' => 'An account with that email already exists.',
'Las contraseñas no coinciden.' => 'The passwords do not match.',
'No se ha podido crear la cuenta.' => 'The account could not be created.',
'Nombre' => 'First name',
'Apellidos' => 'Last name',
'Teléfono' => 'Phone',
'Debe contener al menos ocho caracteres.' => 'Must contain at least eight characters.',
'Repetir contraseña' => 'Repeat password',
'Crear mi cuenta' => 'Create my account',
'¿Ya tienes una cuenta?' => 'Already have an account?',
'Inicia sesión' => 'Log in',
'El nombre es obligatorio.' => 'First name is required.',
'Los apellidos son obligatorios.' => 'Last name is required.',
'El correo electrónico es obligatorio.' => 'Email is required.',
'El correo electrónico no es válido.' => 'The email is not valid.',
'La contraseña debe tener al menos 8 caracteres.' => 'The password must be at least 8 characters long.',
'No se ha podido crear la cuenta' => 'The account could not be created',
'Volver' => 'Back',
'El correo ya está registrado' => 'This email is already registered',
'Cuenta creada correctamente' => 'Account created successfully',
'Ya puedes iniciar sesión.' => 'You can now log in.',

// mi_cuenta.php
'Hola,' => 'Hi,',
'Mis datos' => 'My details',
'Consulta tus próximas actividades y tu historial.' => 'Check your upcoming activities and your history.',
'Ver mis reservas' => 'View my bookings',
'Consulta tus paquetes y los usos disponibles.' => 'Check your packages and remaining uses.',
'Ver mis paquetes' => 'View my packages',

// paquetes.php / comprar_paquete.php
'Paquetes | Sama Shala' => 'Packages | Sama Shala',
'Precios' => 'Pricing',
'Paquetes de clases' => 'Class packages',
'Compra un paquete y utilízalo para reservar las sesiones que quieras mientras tenga usos disponibles.' => 'Buy a package and use it to book as many sessions as you like while it has uses left.',
'No hay paquetes disponibles en este momento.' => 'No packages available right now.',
'clases' => 'classes',
'Válido durante 1 mes desde la compra.' => 'Valid for 1 month from the purchase date.',
'Comprar este paquete' => 'Buy this package',
'El paquete solicitado no existe.' => 'The requested package does not exist.',
'Comprar paquete | Sama Shala' => 'Buy package | Sama Shala',
'Volver a paquetes' => 'Back to packages',
'Clases' => 'Classes',
'Validez' => 'Validity',
'1 mes' => '1 month',
'Precio' => 'Price',
'No se ha podido procesar el pago simulado. Inténtalo de nuevo.' => 'The simulated payment could not be processed. Please try again.',
'Pago simulado' => 'Simulated payment',
'Este proyecto no cobra dinero real: al confirmar se registra la compra directamente como pagada.' => 'This project does not charge real money: confirming registers the purchase as already paid.',
'Nombre del titular' => 'Cardholder name',
'Número de tarjeta (simulado)' => 'Card number (simulated)',
'Confirmar compra de' => 'Confirm purchase of',

// mis_paquetes.php
'Mis paquetes | Sama Shala' => 'My packages | Sama Shala',
'Mis paquetes' => 'My packages',
'Paquete comprado correctamente. Ya puedes usarlo al reservar una sesión.' => 'Package purchased successfully. You can now use it to book a session.',
'Comprar un nuevo paquete' => 'Buy a new package',
'Todavía no tienes ningún paquete.' => 'You don\'t have any packages yet.',
'Usos disponibles:' => 'Uses available:',
'Comprado:' => 'Purchased:',
'Caduca:' => 'Expires:',
'Sin caducidad' => 'No expiration',
'Estado:' => 'Status:',
'Cancelado' => 'Cancelled',
'Caducado' => 'Expired',
'Agotado' => 'Used up',
'Activo' => 'Active',
'Ref. pago:' => 'Payment ref.:',

// mis_reservas.php / lista_espera.php
'Reservas' => 'Bookings',
'Todavía no tienes reservas.' => 'You don\'t have any bookings yet.',
'Pago:' => 'Payment:',
'Con paquete' => 'With package',
'Código:' => 'Code:',
'Cancelar reserva' => 'Cancel booking',
'Confirmada' => 'Confirmed',
'Lista de espera' => 'Waitlist',
'No estás esperando plaza en ninguna sesión.' => 'You are not waiting for a spot in any session.',
'Posición:' => 'Position:',
'Mi lista de espera' => 'My waitlist',
'No estás en lista de espera de ninguna actividad.' => 'You are not on the waitlist for any activity.',
'Esperando' => 'Waiting',
];
